//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOTPIZZA.Models
{
    using global::HOTPIZZA.Models.HOTPIZZA.Models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class Admin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Admin()
        {
            this.TuyenDungs = new HashSet<TuyenDung>();
        }
        [DisplayName("Mã Admin")]
        public int MaAdmin { get; set; }

        [DisplayName("Họ và Tên Admin")]
        public string HovaTen { get; set; }
        [DisplayName("Email")]
        public string Email { get; set; }
        [DisplayName("Số Điện Thoại")]
        public string Phone { get; set; }
        [DisplayName("Tên Đăng Nhập")]
        public string TenDN { get; set; }
        [DisplayName("Mật Khẩu")]
        public string MatKhau { get; set; }
        [DisplayName("Phân Quyền")]
        public Nullable<int> IdPhanQuyen { get; set; }
        [DisplayName("Chi Nhánh")]
        public Nullable<int> IdChiNhanh { get; set; }

        public virtual PhanQuyen PhanQuyen { get; set; }
        public virtual ChiNhanh ChiNhanh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TuyenDung> TuyenDungs { get; set; }
    }
}
