//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System;

namespace HOTPIZZA.Models
{
    public partial class CTDonDatHang
    {
        [Display(Name = "Mã Đơn")]
        public int MaDon { get; set; }

        [Display(Name = "Mã Món Ăn")]
        [Required(ErrorMessage = "Mã món ăn không được để trống")]
        public string MaMon { get; set; }

        [Display(Name = "Số Lượng")]
        [Range(1, int.MaxValue, ErrorMessage = "Số lượng phải lớn hơn 0")]
        public Nullable<int> SoLuong { get; set; }

        [Display(Name = "Đơn Giá")]
        [Range(0, double.MaxValue, ErrorMessage = "Đơn giá phải là số dương")]
        public Nullable<decimal> DonGia { get; set; }

        [Display(Name = "Thành Tiền")]
        [DataType(DataType.Currency)]
        public Nullable<decimal> ThanhTien { get; set; }

        // Các liên kết khóa ngoại
        public virtual DonDatHang DonDatHang { get; set; }
        public virtual MonAn MonAn { get; set; }
    }
}
