//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel;

namespace HOTPIZZA.Models
{
    public partial class DanhMucMon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DanhMucMon()
        {
            this.MonAns = new HashSet<MonAn>();
        }

        [DisplayName("Mã Danh Mục")]  // Adding DisplayName for IdDanhMuc
        public string IdDanhMuc { get; set; }

        [DisplayName("Tên Danh Mục")]  // Adding DisplayName for TenDanhMuc
        public string TenDanhMuc { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonAn> MonAns { get; set; }
    }
}
