//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOTPIZZA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonDatHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonDatHang()
        {
            this.CTDonDatHangs = new HashSet<CTDonDatHang>();
        }
    
        public int MaDon { get; set; }
        public int MaKH { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<decimal> TriGia { get; set; }
        public Nullable<System.DateTime> NgayGiao { get; set; }
        public string TenNguoiNhan { get; set; }
        public string DiaChiNguoiNhan { get; set; }
        public string DienThoaiNguoiNhan { get; set; }
        public Nullable<int> TinhTrangDonHang { get; set; }
        public Nullable<int> HinhThucThanhToan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDonDatHang> CTDonDatHangs { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual TinhTrangDonHang TinhTrangDonHang1 { get; set; }
        public virtual HinhThucThanhToan HinhThucThanhToan1 { get; set; }
    }
}
