//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOTPIZZA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations; // Thêm namespace này

    public partial class DonDatHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonDatHang()
        {
            this.CTDonDatHangs = new HashSet<CTDonDatHang>();
        }

        [Display(Name = "Mã Đơn")]
        public int MaDon { get; set; }

        [Display(Name = "Mã Khách Hàng")]
        public int MaKH { get; set; }

        [Display(Name = "Ngày Đặt")]
        public Nullable<System.DateTime> NgayDat { get; set; }

        [Display(Name = "Trị Giá")]
        public Nullable<decimal> TriGia { get; set; }

        [Display(Name = "Ngày Giao")]
        public Nullable<System.DateTime> NgayGiao { get; set; }

        [Display(Name = "Tên Người Nhận")]
        public string TenNguoiNhan { get; set; }

        [Display(Name = "Địa Chỉ Người Nhận")]
        public string DiaChiNguoiNhan { get; set; }

        [Display(Name = "Điện Thoại Người Nhận")]
        public string DienThoaiNguoiNhan { get; set; }

        [Display(Name = "Tình Trạng Đơn Hàng")]
        public Nullable<int> TinhTrangDonHang { get; set; }

        [Display(Name = "Hình Thức Thanh Toán")]
        public Nullable<int> HinhThucThanhToan { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDonDatHang> CTDonDatHangs { get; set; }
       
        public virtual NguoiDung NguoiDung { get; set; }
        
        public virtual TinhTrangDonHang TinhTrangDonHang1 { get; set; }
        
        public virtual HinhThucThanhToan HinhThucThanhToan1 { get; set; }
    }
}
