//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOTPIZZA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    public partial class Giohang
    {
        HOTPIZZAEntity db = new HOTPIZZAEntity();

        [Display(Name = "Mã Món Ăn")]
        public string IdMon { get; set; }
        [Display(Name = "Tên Món Ăn")]
        public string TenMon { get; set; }

        [Display(Name = "Hình Minh Họa")]
        public string HinhMinhHoa { get; set; }

        [Display(Name = "Số Lượng")]
        public Nullable<int> SoLuong { get; set; }

        [Display(Name = "Đơn Giá")]
        public Nullable<decimal> DonGia { get; set; }

        [Display(Name = "Thành Tiền")]
        public Nullable<decimal> ThanhTien { get { return SoLuong * DonGia; } }

        public Giohang(string IdMon)
        {
            this.IdMon = IdMon;
            MonAn sp = db.MonAns.Single(n => n.IdMon == IdMon);
            TenMon = sp.TenMon;
            HinhMinhHoa = sp.HinhMinhHoa;
            DonGia = decimal.Parse(sp.DonGia.ToString());
            SoLuong = 1;
        }
    }
}