//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOTPIZZA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Login
    {
        HOTPIZZAEntity db= new HOTPIZZAEntity();
        [DisplayName("Tên Đăng Nhập")]
        public string TenDN { get; set; }
        [DisplayName("Tên Đăng Nhập")]
        public string MatKhau { get; set; }
    }
}
