//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOTPIZZA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class MonAn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MonAn()
        {
            this.CTDonDatHangs = new HashSet<CTDonDatHang>();
        }
        [DisplayName("Mã Món")]
        public string IdMon { get; set; }
        [DisplayName("Mã Món")]
        public string TenMon { get; set; }
        [DisplayName("Mã Danh Mục")]
        public string IdDanhMuc { get; set; }
        [DisplayName("Mô Tả")]
        public string MoTa { get; set; }
        [DisplayName("Hình Minh Họa")]
        public string HinhMinhHoa { get; set; }
        [DisplayName("Đơn Giá")]
        public Nullable<decimal> DonGia { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDonDatHang> CTDonDatHangs { get; set; }
        public virtual DanhMucMon DanhMucMon { get; set; }
    }
}
