//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOTPIZZA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class NguoiDung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NguoiDung()
        {
            this.DonDatHangs = new HashSet<DonDatHang>();
            this.GopYKhachHangs = new HashSet<GopYKhachHang>();
        }
        [DisplayName("Mã Khách Hàng")]
        public int MaKhachHang { get; set; }
        [DisplayName("Họ và Tên")]
        public string HovaTen { get; set; }
        [DisplayName("Email")]
        [Required(ErrorMessage = "Email không được để trống")]
        [EmailAddress(ErrorMessage = "Email không đúng định dạng")]
        public string Email { get; set; }
        [DisplayName("Số Điện Thoại")]
        [Required(ErrorMessage = "Số điện thoại không được để trống")]
        [RegularExpression(@"^(\+84|0)\d{9}$", ErrorMessage = "Số điện thoại không đúng định dạng (VD: +849xxxxxxx hoặc 09xxxxxxxx)")]
        public string Phone { get; set; }
        [DisplayName("Ngày Sinh")]
        public Nullable<System.DateTime> NgaySinh { get; set; }
        [DisplayName("Tên Đăng Nhập")]
        public string TenDN { get; set; }
        [DisplayName("Mật Khẩu")]
        public string MatKhau { get; set; }
        [DisplayName("Phân Quyền")]
        public Nullable<int> IdPhanQuyen { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonDatHang> DonDatHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GopYKhachHang> GopYKhachHangs { get; set; }
        public virtual PhanQuyen PhanQuyen { get; set; }
    }
}
