//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOTPIZZA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web.Mvc;

    public partial class TuyenDung
    {
        [DisplayName("Mã Tuyển Dụng")]
        public int IdBaiTuyenDung { get; set; }
        [DisplayName("Mã Tuyển Dụng")]
        public string DiaChiTuyenDung { get; set; }
        [DisplayName("Mã Tuyển Dụng")]
        public string ViTriLamViec { get; set; }
        [DisplayName("Mã Tuyển Dụng")]
        public string EmailLienLac { get; set; }
        [DisplayName("Mã Tuyển Dụng")]
        [AllowHtml]
        public string MoTacCongViec { get; set; }
        [DisplayName("Mã Tuyển Dụng")]
        public int MaAdmin { get; set; }
    
        public virtual Admin Admin { get; set; }
    }
}
